#!/bin/bash

# Generated by ChatGPT

# Default values for options
SOURCE_DIR=""
BASE_DIR=""
DRY_RUN="no"

# Function to display usage
usage() {
    echo "Usage: $0 -s <source-dir> -d <destination-dir> [-n]"
    echo "  -s <source-dir>       Specify the source directory where files are located"
    echo "  -d <destination-dir>  Specify the destination directory for sorted files"
    echo "  -n                    Dry run to show what would be done without moving files"
    exit 1
}

# Parse command-line options
while getopts 's:d:n' option; do
    case "$option" in
        s) SOURCE_DIR=$OPTARG;;
        d) BASE_DIR=$OPTARG;;
        n) DRY_RUN="yes";;
        *) usage;;
    esac
done

# Check if necessary directories are specified
if [ -z "$SOURCE_DIR" ] || [ -z "$BASE_DIR" ]; then
    usage
fi


# Check if source directory exists
if [ ! -d "$SOURCE_DIR" ]; then
    echo "Error: Source directory '$SOURCE_DIR' does not exist."
    exit 1
fi

# Process files
find "$SOURCE_DIR" -maxdepth 1 -type f -print0 | while IFS= read -r -d '' file; do
    # Extract year, month, day
    year=$(date -r "$file" "+%Y")
    month=$(date -r "$file" "+%m")
    day=$(date -r "$file" "+%d")

    # Prepare target directory path
    TARGET_DIR="$BASE_DIR/$year/$month/$day"

    # Print what would be done in dry-run mode
    if [ "$DRY_RUN" = "yes" ]; then
        echo "Would move '$file' to '$TARGET_DIR/'"
    else
        # Create target directory if it doesn't exist
        mkdir -p "$TARGET_DIR"

        # Move file
        mv "$file" "$TARGET_DIR/"
    fi
done

